# Generated by Django 5.1.4 on 2025-01-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField()),
                ('languages', models.JSONField()),
                ('currencies', models.JSONField()),
                ('image_url', models.URLField()),
                ('maps_url', models.URLField(blank=True)),
                ('flag_url', models.URLField()),
            ],
        ),
    ]
