# Generated by Django 5.1.3 on 2024-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0002_rename_trip_mytrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
