# Generated by Django 5.1.4 on 2024-12-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0003_mytrip_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='chosen_hotel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mytrip',
            name='flights_wishlist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mytrip',
            name='hotels_wishlist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activities', models.TextField(blank=True, null=True)),
                ('restaurants_cafes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='user_trips.mytrip')),
            ],
        ),
    ]
