# Generated by Django 5.1.4 on 2024-12-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0004_mytrip_chosen_hotel_id_mytrip_flights_wishlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mytrip',
            name='chosen_hotel_id',
        ),
        migrations.RemoveField(
            model_name='mytrip',
            name='flights_wishlist',
        ),
        migrations.RemoveField(
            model_name='mytrip',
            name='hotels_wishlist',
        ),
        migrations.RemoveField(
            model_name='tripday',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='tripday',
            name='restaurants_cafes',
        ),
        migrations.CreateModel(
            name='DayActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('attraction', 'Attraction'), ('restaurant', 'Restaurant'), ('note', 'Note')], max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='user_trips.tripday')),
                ('list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_trips.listitem')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TripList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('list_type', models.CharField(choices=[('attractions', 'Attractions'), ('restaurants', 'Restaurants'), ('notes', 'Notes'), ('custom', 'Custom List')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='user_trips.mytrip')),
            ],
        ),
        migrations.AddField(
            model_name='listitem',
            name='trip_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_trips.triplist'),
        ),
    ]
