# Generated by Django 5.1.4 on 2024-12-27 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0006_alter_triplist_list_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='trip_list',
        ),
        migrations.RemoveField(
            model_name='triplist',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='mytrip',
            name='image_url',
        ),
        migrations.AddField(
            model_name='mytrip',
            name='attractions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mytrip',
            name='restaurants',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mytrip',
            name='trip_days',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mytrip',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mytrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DayActivity',
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
        migrations.DeleteModel(
            name='TripList',
        ),
    ]
