# Generated by Django 5.1.4 on 2024-12-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0007_remove_listitem_trip_list_remove_triplist_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
