# Generated by Django 5.1.4 on 2024-12-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0010_listitem_alter_mytrip_destination_alter_mytrip_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrip',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='mytrip',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='mytrip',
            name='trip_days',
        ),
    ]
