# Generated by Django 5.1.4 on 2024-12-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0013_remove_listitem_trip_list_remove_tripday_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrip',
            name='attractions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mytrip',
            name='restaurants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
