# Generated by Django 5.1.4 on 2024-12-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0014_alter_mytrip_attractions_alter_mytrip_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('places', models.JSONField(blank=True, default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='user_trips.mytrip')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
