# Generated by Django 5.1.4 on 2025-01-30 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0015_tripday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
