# Generated by Django 5.1.4 on 2025-01-30 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_trips', '0016_mytrip_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mytrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
